import Head from 'next/head'
import React from 'react';
import Footer from '../components/ShareComponents/Footer';
import Navbar from '../components/ShareComponents/Navbar';
// import Footer from '../components/ShareComponents/Footer';
// import Navbar from '../components/ShareComponents/Navbar';
// import MetaLinks from './MetaLinks';

const Layout = ({ children }) => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/* Navbar section  */}
            <Navbar/>

            {/* All meta tags and css links  */}
            {/* <MetaLinks /> */}

            {/* main app children */}
            {children}


            {/* Footer section  */}
            <Footer/>
        </>
    );
};

export default Layout;